# Prometheus configuration for PHP-FPM Runtime Manager monitoring
# Scrapes metrics from manager and exports to Grafana

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'docker'
    cluster: 'phpfpm-manager'

# Rule files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # PHP-FPM Runtime Manager metrics
  - job_name: 'phpfpm-manager'
    static_configs:
      - targets: ['phpfpm-manager:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s

    # Relabel to add instance information
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: phpfpm-manager:9090

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Nginx metrics (if nginx-prometheus-exporter is enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Docker container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    path: /prometheus
    wal-compression: true